### PR TITLE
Feature add base map to map images

### LINKED ISSUE #14: Include map layer on GIS maps
in the GIS maps, the map layer is not visualized, then in the maps with the Facilities - OrgUnits it is not comprehensible - only picture with cycles is visualized:
here examples from our DHIS2 site and from the DEMO server

### LINKED ISSUE #74: The App does not show dashboard items after rotation

### PR DESCRIPTION
**Pull request by xurxodev**
close #14

### CODE REVIEW

**Review by ifoche — COMMENTED** [review]
@xurxodev I didn't find any working map in android-current. Can you provide me with some server/dashboards where the feature can be tested?

**Comment by xurxodev** [comment]
@ifoche I have tested always with android-previous1, on the first dashboards tab appears base map work successfully for some dashboard item

**Review by ifoche — CHANGES_REQUESTED** [review]
@xurxodev this is something that we talked about sometimes but I think we never finally wrote it anywhere. The thing is that due to wrong coordinates coming from the server, most of the maps are showing incorrect areas so that's going to be perceived by the users as a bug. Could we add a checkbox to enable/disable the map layer?

**Comment by xurxodev** [comment]
@ifoche changes are done

**Review by ifoche — APPROVED** [review]
thanks @xurxodev

**Pull request merged**
